"""empty message

Revision ID: a9839a37d9a9
Revises: fe142e180046
Create Date: 2023-05-05 18:47:39.979467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9839a37d9a9'
down_revision = 'fe142e180046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('room', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('deck_json', sa.JSON(), nullable=True),
    sa.Column('dealer_hand_json', sa.JSON(), nullable=True),
    sa.Column('player_hand_json', sa.JSON(), nullable=True),
    sa.Column('current_turn', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
