"""empty message

Revision ID: dc9120627c43
Revises: 1adae0118d2f
Create Date: 2023-05-12 17:41:23.149519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9120627c43'
down_revision = '1adae0118d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_user', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
