"""empty message

Revision ID: ea0a54d6a7d2
Revises: a9839a37d9a9
Create Date: 2023-05-11 17:02:50.867219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0a54d6a7d2'
down_revision = 'a9839a37d9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_game',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('room', sa.String(length=128), nullable=True),
    sa.Column('game_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_room',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('dealer', sa.String(length=128), nullable=True),
    sa.Column('player', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_user',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_user')
    op.drop_table('db_room')
    op.drop_table('db_game')
    # ### end Alembic commands ###
